CREATE TABLE dbo_policy (
                            id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            chdrnum      VARCHAR(8)                              NOT NULL,
                            cownnum      VARCHAR(8)                              NOT NULL,
                            owner_name   VARCHAR(50),
                            lifc_num     VARCHAR(8),
                            lifc_name    VARCHAR(50),
                            aracde       VARCHAR(3),
                            agntnum      VARCHAR(5),
                            mail_address VARCHAR(50),
                            CONSTRAINT "pk_dbo.policy" PRIMARY KEY (id)
);

CREATE TABLE dbo_sur_values (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                chdrnum    VARCHAR(8)                              NOT NULL,
                                survalue   DECIMAL(15, 2),
                                company    VARCHAR(1)                              NOT NULL,
                                currency   VARCHAR(3),
                                valid_date VARCHAR(10),
                                CONSTRAINT "pk_dbo.survalues" PRIMARY KEY (id)
);

CREATE TABLE outpay_header (
                               outpay_header_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               clntnum          VARCHAR(8)                              NOT NULL,
                               chdrnum          VARCHAR(8)                              NOT NULL,
                               letter_type      VARCHAR(12)                             NOT NULL,
                               print_date       TIMESTAMP WITHOUT TIME ZONE,
                               dataid           VARCHAR(6),
                               clnt_name        VARCHAR(80),
                               clnt_address     VARCHAR(80),
                               reg_date         TIMESTAMP WITHOUT TIME ZONE,
                               ben_percent      DECIMAL(6, 2),
                               role1            VARCHAR(2),
                               role2            VARCHAR(2),
                               cown_num         VARCHAR(8),
                               cown_name        VARCHAR(80),
                               notice01         VARCHAR(80),
                               notice02         VARCHAR(80),
                               notice03         VARCHAR(80),
                               notice04         VARCHAR(80),
                               notice05         VARCHAR(80),
                               notice06         VARCHAR(80),
                               claim_id         VARCHAR(9),
                               tp2process_date  TIMESTAMP WITHOUT TIME ZONE,
                               CONSTRAINT pk_outpay_header PRIMARY KEY (outpay_header_id)
);

CREATE TABLE BATCH_JOB_INSTANCE  (
                                     JOB_INSTANCE_ID BIGINT  NOT NULL PRIMARY KEY ,
                                     VERSION BIGINT ,
                                     JOB_NAME VARCHAR(100) NOT NULL,
                                     JOB_KEY VARCHAR(32) NOT NULL,
                                     constraint JOB_INST_UN unique (JOB_NAME, JOB_KEY)
) ;

CREATE TABLE BATCH_JOB_EXECUTION  (
                                      JOB_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                      VERSION BIGINT  ,
                                      JOB_INSTANCE_ID BIGINT NOT NULL,
                                      CREATE_TIME TIMESTAMP NOT NULL,
                                      START_TIME TIMESTAMP DEFAULT NULL ,
                                      END_TIME TIMESTAMP DEFAULT NULL ,
                                      STATUS VARCHAR(10) ,
                                      EXIT_CODE VARCHAR(2500) ,
                                      EXIT_MESSAGE VARCHAR(2500) ,
                                      LAST_UPDATED TIMESTAMP,
                                      constraint JOB_INST_EXEC_FK foreign key (JOB_INSTANCE_ID)
                                          references BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_PARAMS  (
                                             JOB_EXECUTION_ID BIGINT NOT NULL ,
                                             PARAMETER_NAME VARCHAR(100) NOT NULL ,
                                             PARAMETER_TYPE VARCHAR(100) NOT NULL ,
                                             PARAMETER_VALUE VARCHAR(2500) ,
                                             IDENTIFYING CHAR(1) NOT NULL ,
                                             constraint JOB_EXEC_PARAMS_FK foreign key (JOB_EXECUTION_ID)
                                                 references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION  (
                                       STEP_EXECUTION_ID BIGINT  NOT NULL PRIMARY KEY ,
                                       VERSION BIGINT NOT NULL,
                                       STEP_NAME VARCHAR(100) NOT NULL,
                                       JOB_EXECUTION_ID BIGINT NOT NULL,
                                       CREATE_TIME TIMESTAMP NOT NULL,
                                       START_TIME TIMESTAMP DEFAULT NULL ,
                                       END_TIME TIMESTAMP DEFAULT NULL ,
                                       STATUS VARCHAR(10) ,
                                       COMMIT_COUNT BIGINT ,
                                       READ_COUNT BIGINT ,
                                       FILTER_COUNT BIGINT ,
                                       WRITE_COUNT BIGINT ,
                                       READ_SKIP_COUNT BIGINT ,
                                       WRITE_SKIP_COUNT BIGINT ,
                                       PROCESS_SKIP_COUNT BIGINT ,
                                       ROLLBACK_COUNT BIGINT ,
                                       EXIT_CODE VARCHAR(2500) ,
                                       EXIT_MESSAGE VARCHAR(2500) ,
                                       LAST_UPDATED TIMESTAMP,
                                       constraint JOB_EXEC_STEP_FK foreign key (JOB_EXECUTION_ID)
                                           references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE TABLE BATCH_STEP_EXECUTION_CONTEXT  (
                                               STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                               SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                               SERIALIZED_CONTEXT TEXT ,
                                               constraint STEP_EXEC_CTX_FK foreign key (STEP_EXECUTION_ID)
                                                   references BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ;

CREATE TABLE BATCH_JOB_EXECUTION_CONTEXT  (
                                              JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
                                              SHORT_CONTEXT VARCHAR(2500) NOT NULL,
                                              SERIALIZED_CONTEXT TEXT ,
                                              constraint JOB_EXEC_CTX_FK foreign key (JOB_EXECUTION_ID)
                                                  references BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ;

CREATE SEQUENCE BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;