CREATE TABLE dbo_policy (
                            id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                            chdrnum      VARCHAR(8)                              NOT NULL,
                            cownnum      VARCHAR(8)                              NOT NULL,
                            owner_name   VARCHAR(50),
                            lifc_num     VARCHAR(8),
                            lifc_name    VARCHAR(50),
                            aracde       VARCHAR(3),
                            agntnum      VARCHAR(5),
                            mail_address VARCHAR(50),
                            CONSTRAINT "pk_dbo.policy" PRIMARY KEY (id)
);

CREATE TABLE dbo_sur_values (
                                id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                chdrnum    VARCHAR(8)                              NOT NULL,
                                survalue   DECIMAL(15, 2),
                                company    VARCHAR(1)                              NOT NULL,
                                currency   VARCHAR(3),
                                valid_date VARCHAR(10),
                                CONSTRAINT "pk_dbo.survalues" PRIMARY KEY (id)
);

CREATE TABLE outpay_header (
                               outpay_header_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                               clntnum          VARCHAR(8)                              NOT NULL,
                               chdrnum          VARCHAR(8)                              NOT NULL,
                               letter_type      VARCHAR(12)                             NOT NULL,
                               print_date       TIMESTAMP WITHOUT TIME ZONE,
                               dataid           VARCHAR(6),
                               clnt_name        VARCHAR(80),
                               clnt_address     VARCHAR(80),
                               reg_date         TIMESTAMP WITHOUT TIME ZONE,
                               ben_percent      DECIMAL(6, 2),
                               role1            VARCHAR(2),
                               role2            VARCHAR(2),
                               cown_num         VARCHAR(8),
                               cown_name        VARCHAR(80),
                               notice01         VARCHAR(80),
                               notice02         VARCHAR(80),
                               notice03         VARCHAR(80),
                               notice04         VARCHAR(80),
                               notice05         VARCHAR(80),
                               notice06         VARCHAR(80),
                               claim_id         VARCHAR(9),
                               tp2process_date  TIMESTAMP WITHOUT TIME ZONE,
                               CONSTRAINT pk_outpay_header PRIMARY KEY (outpay_header_id)
);